CREATE DATABASE DB_BancoInter;

USE DB_BancoInter;

CREATE TABLE CLIENTES (
    CLIENTE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (50) NOT NULL,
    CPF CHAR (11) NOT NULL UNIQUE,
    TELEFONE VARCHAR (15),
    EMAIL VARCHAR (50),
    SENHA VARCHAR (50)
);

CREATE TABLE CONTAS(
    CONTA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    TIPO_CONTA VARCHAR (10),
    SALDO DECIMAL (15,2) DEFAULT 0.00,
    AGENCIA INT,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE CONTATOS (
    CONTATO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    TIPO_CONTATO VARCHAR(50) NOT NULL,
    VALOR_CONTATO VARCHAR(100) NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE ALERTA_SUSPENSAO (
    ALERTASUSPENSAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    DESCRICAO_ALERTA_SUSPENSAO VARCHAR(500) NOT NULL,
    DATA_REGISTRO DATE NOT NULL,
    SITUACAO VARCHAR(20) NOT NULL,
    MOTIVO VARCHAR(300),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE TRANSACOES (
    TRANSACAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    TIPO_TRANSACAO VARCHAR (15),
    VALOR DECIMAL (15,2) NOT NULL,
    DATA_TRANSACAO DATE,
    FOREIGN KEY (CONTA_ID) REFERENCES CONTAS(CONTA_ID)
);

CREATE TABLE EMPRESTIMO(
    EMPRESTIMO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    VALOR_EMPRESTIMO DECIMAL (15,2) NOT NULL,
    JUROS DECIMAL (5,2) NOT NULL,
    PARCELAS INT,
    DATA_EMPRESTIMO DATE,
    SITUACAO VARCHAR (15),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE CARTOES(
    CARTAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT,
    TIPO_CARTAO VARCHAR (10),
    LIMITE DECIMAL (15,2),
    NUMERO_CARTAO CHAR (16),
    DATA_VENCIMENTO DATE NOT NULL,
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE INVESTIMENTOS(
    INVESTIMENTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT,
    TIPO_INVESTIMENTO VARCHAR(50),
    VALOR_INVESTIDO DECIMAL(18, 2),
    DATA_INVESTIMENTO DATE,
    TAXA_RENDIMENTO DECIMAL(5, 2),
    DATA_VENCIMENTO DATE,
    RENTABILIDADE_ANUAL DECIMAL(5, 2),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE FATURAS(
    FATURA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CARTAO_ID INT,
    DATA_INICIO DATE,
    VENCIMENTO_FATURA DATE,
    VALOR_FATURA DECIMAL (18,2),
    JUROS_FATURA DECIMAL (5,2),
    FOREIGN KEY (CARTAO_ID) REFERENCES CARTOES(CARTAO_ID)
);
